INSERT INTO skills(name,category,description) VALUES
('Python','Programming','Python programming and application development'),
('JavaScript','Programming','JavaScript for web application development'),
('TypeScript','Programming','TypeScript for scalable JavaScript applications'),
('Java','Programming','Java application development'),
('C++','Programming','C++ programming and systems development'),
('HTML','Frontend','Web page structure and semantic HTML'),
('CSS','Frontend','Web styling and responsive design'),
('React','Frontend','Frontend application development with React'),
('Node.js','Backend','Server-side JavaScript development'),
('Express.js','Backend','Backend API development with Express.js'),
('REST API','Backend','Design and development of RESTful APIs'),
('PostgreSQL','Database','Relational database design and SQL'),
('MySQL','Database','MySQL database development'),
('MongoDB','Database','NoSQL database development'),
('SQL','Database','Structured Query Language and relational databases'),
('Git','Tools','Version control with Git'),
('GitHub','Tools','Source code collaboration and open source development'),
('Docker','DevOps','Containerization and application deployment'),
('AWS','Cloud','Cloud computing and AWS services'),
('Azure','Cloud','Cloud computing and Microsoft Azure services'),
('Pandas','Data Science','Data manipulation and analysis with Pandas'),
('NumPy','Data Science','Numerical computing with NumPy'),
('Scikit-learn','Data Science','Machine learning with Scikit-learn'),
('TensorFlow','Machine Learning','Deep learning with TensorFlow'),
('Machine Learning','AI','Machine learning concepts and algorithms'),
('Data Analysis','Data Science','Data analysis and exploratory data analysis'),
('Power BI','Data Analytics','Business intelligence and visualization'),
('Excel','Data Analytics','Spreadsheet analysis and reporting'),
('DBMS','Database','Database management systems'),
('Problem Solving','Professional','Analytical and problem-solving skills'),
('Communication','Professional','Professional communication skills'),
('Agile','Professional','Agile software development practices'),
('Linux','DevOps','Linux operating system and command-line administration')
ON CONFLICT(name) DO NOTHING;

INSERT INTO career_roles(title,description,industry,growth_outlook) VALUES
('Full Stack Developer','Develops complete web applications across frontend and backend systems.','Software','High'),
('Backend Developer','Builds APIs, backend services, databases and server-side applications.','Software','High'),
('Frontend Developer','Builds responsive and interactive web applications.','Software','High'),
('Data Analyst','Analyzes data and creates insights, dashboards and reports for business decisions.','Data','High'),
('Data Scientist','Uses statistics, programming and machine learning to solve data problems.','Data','High'),
('Machine Learning Engineer','Builds, deploys and maintains machine learning systems.','Artificial Intelligence','Very High'),
('Data Engineer','Builds data pipelines, storage systems and infrastructure for analytics.','Data','Very High'),
('Software Engineer','Designs, develops, tests and maintains scalable software systems.','Software','Very High'),
('Cloud Engineer','Designs and manages cloud infrastructure and deployment systems.','Cloud','Very High'),
('DevOps Engineer','Automates software delivery, infrastructure and deployment processes.','Cloud','Very High'),
('Business Intelligence Analyst','Transforms business data into dashboards and actionable insights.','Analytics','High'),
('AI Engineer','Develops applications and systems using artificial intelligence technologies.','Artificial Intelligence','Very High')
ON CONFLICT(title) DO NOTHING;
